const catchTbl = [
   
    {
        ID: 2,
        Species: "LMB",
        CatchDate: "2010-04-26",
        Trip: "Murray1",
        Location: "Under wires",
        Angler: "Willie",
        Quantity: 1,
        Weight: 5,
        Length: 24,
        Girth: 26,
        FightTime: 4,
        Outcome: "Released",
        Style: "Texas",
        Bait: "Senko",
        BaitColor: "green",
        Notes: "blah blah",
        AirTemp: 69,
        WindDirection: "s",
        Wind: "breezy",
        SkyCondition: "cloudy",
        LunarPhase: "Full",
        Pressure: 44,
        Barometer: 48,
        WaterTemp: 65,
        WaterDepth: 20,
        WaterPh: 1,
        Current: 4,
        Bottom: "rocky",
        WaterColor: "clear",
        Tide: "n/a",
        WaterLevel: "high",
        Seas: "rough",
        Rod: "Shimano",
        Reel: "Shimano",
        HookSize: 4,
        HookType: "Circle",
        SinkerWeight: 2.25,
        SinkerStyle: "split shot",
        LineTest: 10,
        LineStyle: "Mono",
        LineColor: "Clear",
        ImgCaption: "Chuckawalla Lizard",
        Photo: "None"
    },
    {
        ID: 3,
        Species: "Catfish",
        CatchDate: "2010-04-26",
        Trip: "Murray3",
        Location: "Under wires",
        Angler: "Marlo",
        Quantity: 1,
        Weight: 10,
        Length: 24,
        Girth: 26,
        FightTime: 10,
        Outcome: "Released",
        Style: "Texas",
        Bait: "Shiner",
        BaitColor: "silver",
        Notes: "Biggest catfish caught",
        AirTemp: 72,
        WindDirection: "sw",
        Wind: "light",
        SkyCondition: "Clear",
        LunarPhase: "Full",
        Pressure: 34,
        Barometer: 45,
        WaterTemp: 63,
        WaterDepth: 20,
        WaterPh: 9,
        Current: 3,
        Bottom: "flat",
        WaterColor: "murky",
        Tide: "low",
        WaterLevel: "n/a",
        Seas: "calm",
        Rod: "Shimano",
        Reel: "Penn",
        HookSize: 4,
        HookType: "Circle",
        SinkerWeight: 2.25,
        SinkerStyle: "split shot",
        LineTest: 25,
        LineStyle: "Braid",
        LineColor: "Clear",
        ImgCaption: "Big Fish",
        Photo: "None"
    },
    {
        ID: 4,
        Species: "Shark",
        CatchDate: "02-24-2018",
        Trip: "Pacific",
        Location: "60 mile bank",
        Angler: "Willie",
        Quantity: 1,
        Weight: 60,
        Length: 124,
        Girth: 126,
        FightTime: 30,
        Outcome: "Released",
        Style: "fly line",
        Bait: "squid",
        BaitColor: "silver",
        Notes: "big shark",
        AirTemp: 82,
        WindDirection: "w",
        Wind: "light",
        SkyCondition: "Clear",
        LunarPhase: "waxxing",
        Pressure: 34,
        Barometer: 45,
        WaterTemp: 68,
        WaterDepth: 90,
        WaterPh: 3,
        Current: 0,
        Bottom: "rocky",
        WaterColor: "murky",
        Tide: "slack",
        WaterLevel: "n/a",
        Seas: "calm",
        Rod: "Shimano",
        Reel: "Penn",
        HookSize: 6,
        HookType: "Circle",
        SinkerWeight: .00,
        SinkerStyle: "none",
        LineTest: 100,
        LineStyle: "Braid",
        LineColor: "green",
        ImgCaption: "Big Shark",
        Photo: "None"
    },
    {
        ID: 5,
        Species: "LMB",
        CatchDate: "2010-04-26",
        Trip: "Murray1",
        Location: "Under wires",
        Angler: "Willie",
        Quantity: 1,
        Weight: 5,
        Length: 24,
        Girth: 26,
        FightTime: 4,
        Outcome: "Released",
        Style: "Texas",
        Bait: "Senko",
        BaitColor: "green",
        Notes: "blah blah",
        AirTemp: 75,
        WindDirection: "s",
        Wind: "strong",
        SkyCondition: "cloudy",
        LunarPhase: "Full",
        Pressure: 34,
        Barometer: 45,
        WaterTemp: 65,
        WaterDepth: 20,
        WaterPh: 2,
        Current: 5,
        Bottom: "rocky",
        WaterColor: "clear",
        Tide: "high",
        WaterLevel: "n/a",
        Seas: "calm",
        Rod: "Shimano",
        Reel: "Shimano",
        HookSize: 4,
        HookType: "Circle",
        SinkerWeight: 2.25,
        SinkerStyle: "split shot",
        LineTest: 10,
        LineStyle: "Mono",
        LineColor: "Clear",
        ImgCaption: "Chuckawalla Lizard",
        Photo: "None"
    },
    {
        ID: 6,
        Species: "Bluegill",
        CatchDate: "2010-04-26",
        Trip: "Murray2",
        Location: "Under wires",
        Angler: "Marlo",
        Quantity: 1,
        Weight: 10,
        Length: 24,
        Girth: 26,
        FightTime: 10,
        Outcome: "Released",
        Style: "Texas",
        Bait: "worm",
        BaitColor: "silver",
        Notes: "Biggest bluegill caught",
        AirTemp: 85,
        WindDirection: "sw",
        Wind: "strong",
        SkyCondition: "Clear",
        LunarPhase: "Full",
        Pressure: 34,
        Barometer: 45,
        WaterTemp: 63,
        WaterDepth: 20,
        WaterPh: 2,
        Current: 2,
        Bottom: "flat",
        WaterColor: "murky",
        Tide: "high",
        WaterLevel: "high",
        Seas: "calm",
        Rod: "Shimano",
        Reel: "Penn",
        HookSize: 8,
        HookType: "Circle",
        SinkerWeight: 2.25,
        SinkerStyle: "split shot",
        LineTest: 25,
        LineStyle: "Braid",
        LineColor: "Clear",
        ImgCaption: "Big Fish",
        Photo: "None"
    },
    {
        ID: 7,
        Species: "LMB",
        CatchDate: "02-24-2018",
        Trip: "MCR 2",
        Location: "by bridge",
        Angler: "Willie",
        Quantity: 1,
        Weight: 60,
        Length: 124,
        Girth: 126,
        FightTime: 30,
        Outcome: "Released",
        Style: "fly line",
        Bait: "squid",
        BaitColor: "silver",
        Notes: "big shark",
        AirTemp: 69,
        WindDirection: "w",
        Wind: "breezy",
        SkyCondition: "Clear",
        LunarPhase: "waxxing",
        Pressure: 34,
        Barometer: 45,
        WaterTemp: 68,
        WaterDepth: 90,
        WaterPh: 2,
        Current: 0,
        Bottom: "rocky",
        WaterColor: "murky",
        Tide: "n/a",
        WaterLevel: "high",
        Seas: "rough",
        Rod: "Shimano",
        Reel: "Penn",
        HookSize: 4,
        HookType: "Circle",
        SinkerWeight: .00,
        SinkerStyle: "none",
        LineTest: 100,
        LineStyle: "Braid",
        LineColor: "green",
        ImgCaption: "Big Shark",
        Photo: "None"
    },
    {
        ID: 8,
        Species: "Sunfish",
        CatchDate: "04-16-2018",
        Trip: "Lake Jennings 5",
        Location: "60 mile bank",
        Angler: "Willie",
        Quantity: 1,
        Weight: 2,
        Length: 124,
        Girth: 126,
        FightTime: 30,
        Outcome: "Released",
        Style: "fly line",
        Bait: "worm",
        BaitColor: "red",
        Notes: "big sunfish",
        AirTemp: 78,
        WindDirection: "w",
        Wind: "none",
        SkyCondition: "Clear",
        LunarPhase: "waxxing",
        Pressure: 34,
        Barometer: 45,
        WaterTemp: 68,
        WaterDepth: 90,
        WaterPh: 2,
        Current: 0,
        Bottom: "sand",
        WaterColor: "murky",
        Tide: "low",
        WaterLevel: "high",
        Seas: "mild",
        Rod: "Shimano",
        Reel: "Penn",
        HookSize: 3,
        HookType: "round",
        SinkerWeight: .25,
        SinkerStyle: "slip weight",
        LineTest: 100,
        LineStyle: "Braid",
        LineColor: "green",
        ImgCaption: "Big Shark",
        Photo: "None"
    },
    {
        ID: 9,
        Species: "Bluegill",
        CatchDate: "2010-04-26",
        Trip: "Murray9",
        Location: "at drain",
        Angler: "Willie",
        Quantity: 1,
        Weight: 5,
        Length: 24,
        Girth: 26,
        FightTime: 4,
        Outcome: "Released",
        Style: "Texas",
        Bait: "Senko",
        BaitColor: "green",
        Notes: "blah blah",
        AirTemp: 87,
        WindDirection: "s",
        Wind: "strong",
        SkyCondition: "cloudy",
        LunarPhase: "Full",
        Pressure: 34,
        Barometer: 45,
        WaterTemp: 65,
        WaterDepth: 20,
        WaterPh: 2,
        Current: 2,
        Bottom: "rocky",
        WaterColor: "clear",
        Tide: "high",
        WaterLevel: "high",
        Seas: "rough",
        Rod: "Shimano",
        Reel: "Shimano",
        HookSize: 4,
        HookType: "Circle",
        SinkerWeight: 2.25,
        SinkerStyle: "split shot",
        LineTest: 15,
        LineStyle: "Mono",
        LineColor: "Clear",
        ImgCaption: "Lizard",
        Photo: "None"
    },
    {
        ID: 10,
        Species: "SMB",
        CatchDate: "2010-04-26",
        Trip: "Murray10",
        Location: "san carlos bay",
        Angler: "Marlo",
        Quantity: 10,
        Weight: 10,
        Length: 24,
        Girth: 26,
        FightTime: 10,
        Outcome: "Released",
        Style: "Texas",
        Bait: "topwater",
        BaitColor: "silver",
        Notes: "Biggest smallmouth caught",
        AirTemp: 69,
        WindDirection: "sw",
        Wind: "light",
        SkyCondition: "Clear",
        LunarPhase: "Full",
        Pressure: 34,
        Barometer: 45,
        WaterTemp: 63,
        WaterDepth: 15,
        WaterPh: 2,
        Current: 2,
        Bottom: "flat",
        WaterColor: "murky",
        Tide: "high",
        WaterLevel: "high",
        Seas: "rough",
        Rod: "Shimano",
        Reel: "Penn",
        HookSize: 6,
        HookType: "squid",
        SinkerWeight: .00,
        SinkerStyle: "none",
        LineTest: 25,
        LineStyle: "Braid",
        LineColor: "Clear",
        ImgCaption: "Fish",
        Photo: "None"
    },
    {
        ID: 11,
        Species: "LMB",
        CatchDate: "02-24-2018",
        Trip: "Lake Murray 11",
        Location: "By dock",
        Angler: "Marlo",
        Quantity: 1,
        Weight: 60,
        Length: 124,
        Girth: 126,
        FightTime: 30,
        Outcome: "Released",
        Style: "texas rig",
        Bait: "rattletrap",
        BaitColor: "green",
        Notes: "big bass",
        AirTemp: 54,
        WindDirection: "w",
        Wind: "light",
        SkyCondition: "Clear",
        LunarPhase: "waning",
        Pressure: 34,
        Barometer: 45,
        WaterTemp: 68,
        WaterDepth: 10,
        WaterPh: 2,
        Current: 0,
        Bottom: "sandy",
        WaterColor: "murky",
        Tide: "high",
        WaterLevel: "high",
        Seas: "calm",
        Rod: "Quantuum",
        Reel: "Penn",
        HookSize: 8,
        HookType: "Circle",
        SinkerWeight: .25,
        SinkerStyle: "split shot",
        LineTest: 20,
        LineStyle: "Braid",
        LineColor: "green",
        ImgCaption: "Big Bass",
        Photo: "None"
    }

]

export default catchTbl;