const TripTbl = [
    {
        ID: "id",
        Trip: "Trip Name",
        StartDate: "Start Date",
        Duration: "Duration",
        Place: "Location",
        Photos: "Photos",
        Notes: "Notes",
        Anglers: "Anglers",
        GPS1: "GPS1",
        GPS2: "GPS2",
        ImgCaption: "Photo Caption"
    },
    {
        ID: 2,
        Trip: "Lake Murray1",
        StartDate: "06-10-2018",
        Duration: 2,
        Place: "By dock",
        Photos: "F:\\D_Drive\\bass10.jpg",
        Notes: "cloudy sky",
        Anglers: "Willie, Marlo",
        GPS1: "N23.234",
        GPS2: "W34.567",
        ImgCaption: "big fish"
    },
    {
        ID: 3,
        Trip: "Lake Murray2",
        StartDate: "04-18-2018",
        Duration: "1 hour",
        Place: "Under tree",
        Photos: "F:\\D_Drive\\bass2.jpg",
        Notes: "cloudy sky",
        Anglers: "Willie, Marlo",
        GPS1: "N65.234",
        GPS2: "W34.567",
        ImgCaption: "fish size"
    },
    {
        ID: 4,
        Trip: "Lake Jennings",
        StartDate: "12-15-2017",
        Duration: "3 hours",
        Place: "in boat",
        Photos: "F:\\D_Drive\\bass4.jpg",
        Notes: "hot",
        Anglers: "Marlo",
        GPS1: "N54.200",
        GPS2: "W33.567",
        ImgCaption: "fish"
    },
    {
        ID: 5,
        Trip: "Lake Murray4",
        StartDate: "07-13-2018",
        Duration: 2,
        Place: "By dock",
        Photos: "F:\\D_Drive\\bass-14.jpg",
        Notes: "sunny sky",
        Anglers: "Willie, Marlo",
        GPS1: "N13.205",
        GPS2: "W74.509",
        ImgCaption: "big fish"
    },
    {
        ID: 6,
        Trip: "MCR",
        StartDate: "10-22-2018",
        Duration: 3,
        Place: "under bridge",
        Photos: "F:\\D_Drive\\bass-34.jpg",
        Notes: "hot",
        Anglers: "Marlo",
        GPS1: "N13.208",
        GPS2: "W34.567",
        ImgCaption: "a fighter"
    },
    {
        ID: 7,
        Trip: "Lake Murray2",
        StartDate: "04-18-2018",
        Duration: 4,
        Place: "Under tree",
        Photos: "F:\\D_Drive\\bass2.jpg",
        Notes: "cloudy sky",
        Anglers: "Willie, Marlo",
        GPS1: "N23.234",
        GPS2: "W22.567",
        ImgCaption: "fish size"
    },
    {
        ID: 8,
        Trip: "Lake Jennings",
        StartDate: "12-15-2017",
        Duration: 2,
        Place: "in boat",
        Photos: "F:\\D_Drive\\bass4.jpg",
        Notes: "hot",
        Anglers: "Marlo",
        GPS1: "N23.234",
        GPS2: "W34.567",
        ImgCaption: "great day"
    },
    {
        ID: 9,
        Trip: "Lake Murray4",
        StartDate: "07-13-2018",
        Duration: 1,
        Place: "By dock",
        Photos: "F:\\D_Drive\\bass-14.jpg",
        Notes: "sunny sky",
        Anglers: "Willie, Marlo",
        GPS1: "N20.234",
        GPS2: "W74.509",
        ImgCaption: "big fish"
    },
    {
        ID: 10,
        Trip: "MCR",
        StartDate: "10-22-2018",
        Duration: "1 day",
        Place: "under bridge",
        Photos: "F:\\D_Drive\\bass-34.jpg",
        Notes: "hot",
        Anglers: "Marlo",
        GPS1: "N23.234",
        GPS2: "W14.567",
        ImgCaption: "personal record"
    }
]

export default TripTbl;