const CatchHeaders = [
    { Header: "Species", accessor: "Species",},
    { Header: "Trip Name", accessor: "Trip",},
    { Header: "Catch Date", accessor: "CatchDate"},
    { Header: "Location", accessor: "Location",},
    { Header: "Angler", accessor: "Angler",},
    { Header: "Quantity", accessor: "Quantity"},
    { Header: "Weight", accessor: "Weight",},
    { Header: "Trip", accessor: "Trip",},
    { Header: "CatchDate", accessor: "CatchDate" },
    { Header: "FightTime", accessor: "FightTime",},
    { Header: "Outcome", accessor: "Outcome",},
    { Header: "Style", accessor: "Style"},
    { Header: "Bait", accessor: "Bait",},
    { Header: "BaitColor", accessor: "BaitColor",},
    { Header: "Notes", accessor: "Notes"},
    { Header: "AirTemp", accessor: "AirTemp",},
    { Header: "WindDirection", accessor: "WindDirection",},
    { Header: "Wind", accessor: "Wind"},       
    { Header: "Sky Condition", accessor: "SkyCondition",},
    { Header: "Lunar Phase", accessor: "LunarPhase",},
    { Header: "Pressure", accessor: "Pressure"},
    { Header: "Barometer", accessor: "Barometer",},
    { Header: "Water Temp", accessor: "WaterTemp",},
    { Header: "Water Depth", accessor: "WaterDepth" },
    { Header: "Water Ph", accessor: "WaterPh",},
    { Header: "Current", accessor: "Current",},
    { Header: "Bottom", accessor: "Bottom" },
    { Header: "Water Color", accessor: "WaterColor",},
    { Header: "Tide", accessor: "Tide",},
    { Header: "Water Level", accessor: "WaterLevel"},
    { Header: "Seas", accessor: "Seas",},
    { Header: "Rod", accessor: "Rod",},
    { Header: "Reel", accessor: "Reel"},
    { Header: "Hook Size", accessor: "HookSize",},
    { Header: "Hook Type", accessor: "HookType",},
    { Header: "Sinker Type", accessor: "SinkerWeight"},      
    { Header: "Location", accessor: "SinkerStyle",},
    { Header: "Line Test(Lb.)", accessor: "LineTest",},
    { Header: "Line Type", accessor: "LineStyle"},
    { Header: "Line Color", accessor: "LineColor",},
    { Header: "Image Caption", accessor: "ImgCaption",},
    { Header: "Image", accessor: "Photo"},   
]