const CatchHeaders = [
    { Header: "Species", accessor: "Species", width: 150},
    { Header: "Trip Name", accessor: "Trip", width: 150},
    { Header: "Catch Date", accessor: "CatchDate",},
    { Header: "Location", accessor: "Location", width: 150},
    { Header: "Angler", accessor: "Angler",},
    { Header: "Qty", accessor: "Quantity", width: 75,},
    { Header: "Weight", accessor: "Weight", width: 75, },
    { Header: "Trip", accessor: "Trip",},
    { Header: "Catch Date", accessor: "CatchDate"},
    { Header: "Fight Time", accessor: "FightTime",},
    { Header: "Outcome", accessor: "Outcome",},
    { Header: "Fishing Style", accessor: "Style"},
    { Header: "Bait Type", accessor: "Bait",},
    { Header: "Bait Color", accessor: "BaitColor",},
    { Header: "Notes", accessor: "Notes", width: 200,},
    { Header: "Air Temp", accessor: "AirTemp",},
    { Header: "Wind Direction", accessor: "WindDirection",},
    { Header: "Wind", accessor: "Wind"},       
    { Header: "Sky", accessor: "SkyCondition",},
    { Header: "Lunar Phase", accessor: "LunarPhase",},
    { Header: "Pressure", accessor: "Pressure"},
    { Header: "Barometer", accessor: "Barometer",},
    { Header: "Water Temp", accessor: "WaterTemp",},
    { Header: "Water Depth", accessor: "WaterDepth" },
    { Header: "Water Ph", accessor: "WaterPh",},
    { Header: "Current", accessor: "Current", width: 100},
    { Header: "Bottom", accessor: "Bottom" },
    { Header: "Water Color", accessor: "WaterColor",},
    { Header: "Tide", accessor: "Tide", width: 75},
    { Header: "Water Level", accessor: "WaterLevel"},
    { Header: "Seas", accessor: "Seas", width: 75,},
    { Header: "Rod (Model/Manf)", accessor: "Rod", width: 150,},
    { Header: "Reel (Model/Manf)", accessor: "Reel", width: 150},
    { Header: "Hook Size", accessor: "HookSize",},
    { Header: "Hook Type", accessor: "HookType",},
    { Header: "Sinker Weight", accessor: "SinkerWeight"},      
    { Header: "Sinker Style", accessor: "SinkerStyle",},
    { Header: "Line Test(Lb.)", accessor: "LineTest",},
    { Header: "Line Type", accessor: "LineStyle"},
    { Header: "Line Color", accessor: "LineColor",},
    { Header: "Image Caption", accessor: "ImgCaption",},
    { Header: "Image", accessor: "Photo"},   
]

export default CatchHeaders;