const catchTbl = [
    {
        ID: 1,
        Species: "Species",
        CatchDate: "Catch Date",
        Trip: "Trip Name",
        Location: "Location",
        Angler: "Angler",
        Quantity: 'Quantity',
        Weight: "Weight",
        Length: "Length",
        Girth: "Girth",
        FightTime: "Fight Time",
        Outcome: "Outcome",
        Style: "Fishing Style",
        Bait: "Bait Type",
        BaitColor: "Bait Color",
        Notes: "Notes",
        AirTemp: "Air Temp",
        WindDirection: "Wind Direction",
        Wind: "Wind Speed(mph)",
        SkyCondition: "Sky Condition",
        LunarPhase: "Lunar Phase",
        Pressure: "Pressure",
        Barometer: "Barometer",
        WaterTemp: "Water Temp",
        WaterDepth: "Water Depth",
        WaterPh: "Water Ph",
        Current: "Current Speed",
        Bottom: "Bottom Surface",
        WaterColor: "Water Color",
        Tide: "Tide",
        WaterLevel: "Water Level",
        Seas: "Sea Condition",
        Rod: "Rod (Model/Manf)",
        Reel: "Reel (Model/Manf)",
        HookSize: "Hook Size",
        HookType: "Hook Type",
        SinkerWeight: "Sinker Weight",
        SinkerStyle: "Sinker Type",
        LineTest: "Line Test(Lb.)",
        LineStyle: "Line Type",
        LineColor: "Line Color",
        ImgCaption: "Image Caption",
        Photo: "Image"
    },
    {
        ID: 2,
        Species: "LMB",
        CatchDate: "2010-04-26T00:00:00",
        Trip: "Murray1",
        Location: "Under wires",
        Angler: "Willie",
        Quantity: 1,
        Weight: 5,
        Length: 24,
        Girth: 26,
        FightTime: 4,
        Outcome: "Released",
        Style: "Texas",
        Bait: "Senko",
        BaitColor: "green",
        Notes: "blah blah",
        AirTemp: 69,
        WindDirection: "s",
        Wind: "strong",
        SkyCondition: "cloudy",
        LunarPhase: "Full",
        Pressure: 34,
        Barometer: 45,
        WaterTemp: 65,
        WaterDepth: 20,
        WaterPh: 2,
        Current: 2,
        Bottom: "rocky",
        WaterColor: "clear",
        Tide: "high",
        WaterLevel: "high",
        Seas: "rough",
        Rod: "Shimano",
        Reel: "Shimano",
        HookSize: 4,
        HookType: "Circle",
        SinkerWeight: 2.25,
        SinkerStyle: "split shot",
        LineTest: 10,
        LineStyle: "Mono",
        LineColor: "Clear",
        ImgCaption: "Chuckawalla Lizard",
        Photo: "None"
    },
    {
        ID: 3,
        Species: "Catfish",
        CatchDate: "2010-04-26T00:00:00",
        Trip: "Murray1",
        Location: "Under wires",
        Angler: "Marlo",
        Quantity: 1,
        Weight: 10,
        Length: 24,
        Girth: 26,
        FightTime: 10,
        Outcome: "Released",
        Style: "Texas",
        Bait: "Shiner",
        BaitColor: "silver",
        Notes: "Biggest catfish caught",
        AirTemp: 69,
        WindDirection: "sw",
        Wind: "strong",
        SkyCondition: "Clear",
        LunarPhase: "Full",
        Pressure: 34,
        Barometer: 45,
        WaterTemp: 63,
        WaterDepth: 20,
        WaterPh: 2,
        Current: 2,
        Bottom: "flat",
        WaterColor: "murky",
        Tide: "high",
        WaterLevel: "high",
        Seas: "rough",
        Rod: "Shimano",
        Reel: "Penn",
        HookSize: 4,
        HookType: "Circle",
        SinkerWeight: 2.25,
        SinkerStyle: "split shot",
        LineTest: 25,
        LineStyle: "Braid",
        LineColor: "Clear",
        ImgCaption: "Big Fish",
        Photo: "None"
    },
    {
        ID: 4,
        Species: "Shark",
        CatchDate: "02-24-2018",
        Trip: "Pacific",
        Location: "60 mile bank",
        Angler: "Willie",
        Quantity: 1,
        Weight: 60,
        Length: 124,
        Girth: 126,
        FightTime: 30,
        Outcome: "Released",
        Style: "fly line",
        Bait: "squid",
        BaitColor: "silver",
        Notes: "big shark",
        AirTemp: 69,
        WindDirection: "w",
        Wind: "strong",
        SkyCondition: "Clear",
        LunarPhase: "waxxing",
        Pressure: 34,
        Barometer: 45,
        WaterTemp: 68,
        WaterDepth: 90,
        WaterPh: 2,
        Current: 0,
        Bottom: "rocky",
        WaterColor: "murky",
        Tide: "high",
        WaterLevel: "high",
        Seas: "rough",
        Rod: "Shimano",
        Reel: "Penn",
        HookSize: 4,
        HookType: "Circle",
        SinkerWeight: .25,
        SinkerStyle: "split shot",
        LineTest: 100,
        LineStyle: "Braid",
        LineColor: "green",
        ImgCaption: "Big Shark",
        Photo: "None"
    }

]

export default catchTbl;